'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Actualización
    
    '''<summary>
    '''id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents id As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''cns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cns As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''nom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents nom As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''apl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents apl As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''usr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents usr As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''mal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mal As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''tlf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tlf As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''psw control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents psw As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Act control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Act As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''bck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bck As Global.System.Web.UI.WebControls.Button
End Class
